#!/bin/bash

set -e

new() {
  echo -n "Nombre de la nota: "
  read TITULO
  DATE=`date +%Y-%m-%d`
  FILENAME="es/_posts/$DATE-${TITULO// /-}.markdown"
  echo "---
---

" >> $FILENAME
  vi $FILENAME
}

case "$1" in
  new) new;;
  *)
    echo "USAGE: blog [new]";;
esac

